name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/semantic-release-plugins-release.yml@main
    secrets: inherit
