name: Dependabot auto-merge & tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_call:

jobs:
  tests:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/semantic-release-plugins-test.yml@main
    secrets: inherit
